### PR TITLE
Super Smash Bros Brawl Sfx

### PR DESCRIPTION
**Pull request by Rickopher**
# REPLACE_WITH_PACK_NAMES

https://github.com/Rickopher/Steam-Deck-Sound-Sfx/tree/main/Smash%20Bros.%20Brawl%20Sfx

Insert a link to the GitHub repository of the pack.

### Requirements Agreement

Failure to check the box below by writing an X between the brackets will result in the closing of your pull request. Please write any comments regarding issues with the requirements below.

- [X] I have read [the pack requirements](https://github.com/EMERALD0874/AudioLoader-PackDB#-requirements). I understand that if my pull request does not meet them, it will be closed and I may be banned from the pack database.

### CODE REVIEW

**Comment by Rickopher** [comment]
For music I know we are allowed to upload our own original compositions, system menu soundtracks?, and music with permission/credit to the artist. But if I wanted to upload a song from a game soundtrack (in-game menu tracks, themes I think work for the Steam Deck) and gave credit to the artist, would I be able to upload the song?

**Review by EMERALD0874 — COMMENTED** [review]
The album art you uploaded is not square, so part of it will be cut off. Is that okay with you?

> But if I wanted to upload a song from a game soundtrack [...] would I be able to upload the song?

It may be considered a copyright violation even if proper credit is given. We do not allow people to upload most works others have created for that reason.

**Comment by Rickopher** [comment]
just replaced the image with a better fitting one

**Comment by Rickopher** [comment]
Thanks for the clarification on music as well

**Review by EMERALD0874 — APPROVED** [review]
LGTM. Sorry for the super late review, had finals and a bunch of other stuff going on.

**Pull request merged**
