### PR TITLE
Slime-Pack

### PR DESCRIPTION
**Pull request by CaviarTheCatgirl**
Adding the Image + Pack.json for the "Slime-Pack" by DarkSide1305

# Slime-Pack

[Insert a link to the GitHub repository of the pack.](https://github.com/DarkSide1305/AudioPacks)

### Checklist

Failure to complete this checklist or deleting boxes from the checklist will result in the closing of your pull request unless this is a pack update. Please write any comments regarding this checklist at the bottom of your pull request.

Check every box.

- [x] I am the original author of this pack or have permission from the original author to make this pull request.
- [x] All copyright of this pack's contents belong to the listed author or is cited in the description and repository linked above.
- [x] This theme works properly on the latest versions of SteamOS for Steam Deck, [decky-loader](https://github.com/SteamDeckHomebrew/decky-loader) and [SDH-AudioLoader](https://github.com/EMERALD0874/SDH-AudioLoader).
- [x] This pack is under 10MB in size and uses the least disk space possible.
- [x] This pack is safe for work and does not contain any sexual, drug-related, or profane content.
- [x] This pack does not contain loud, distorted, or otherwise bad faith sound files.
- [x] This pack is only for either music or sounds and only adds or modifies the intended sound files.

### CODE REVIEW

**Review by EMERALD0874 — CHANGES_REQUESTED** [review]
Missing `deck_ui_tab_transition_01.wav` in ignore and files. Please choose to either replace the sound or ignore it.

**Comment by CaviarTheCatgirl** [comment]
Whoops, seems like I missed that one sound effect. Added the Sound Effect to my pack repo and updated the repo commit

**Comment by EMERALD0874** [comment]
I apologize for the delay in review, but we're currently investigating a new CDN solution as we're maxing out our daily traffic with our current solution. This pull request will be reviewed once we have updated the repo to use our new CDN.

**Review by EMERALD0874 — APPROVED** [review]
Looks good to me! Now to hope the changes to our CDN work...

**Pull request merged**
