### PR TITLE
Halo Theme Song

### PR DESCRIPTION
**Pull request by Jmotz85**
# Insert Pack Name(s) Here
Halo Theme
Insert a link to the GitHub repository of the pack.
https://github.com/Jmotz85/Halo-Theme
### Checklist

Failure to complete this checklist or deleting boxes from the checklist will result in the closing of your pull request unless this is a pack update. Please write any comments regarding this checklist at the bottom of your pull request.

Check every box.

- [x] I am the original author of this pack or have permission from the original author to make this pull request.
- [x] All copyright of this pack's contents belong to the listed author or is cited in the description and repository linked above.
- [x] This theme works properly on the latest versions of SteamOS for Steam Deck, [decky-loader](https://github.com/SteamDeckHomebrew/decky-loader) and [SDH-AudioLoader](https://github.com/EMERALD0874/SDH-AudioLoader).
- [x] This pack is under 10MB in size and uses the least disk space possible.
- [x] This pack is safe for work and does not contain any sexual, drug-related, or profane content.
- [x] This pack does not contain loud, distorted, or otherwise bad faith sound files.
- [x] This pack is only for either music or sounds and only adds or modifies the intended sound files.

### CODE REVIEW

**Comment by CaviarTheCatgirl** [comment]
Saw this hasnt been responded too yet, you need to make a Folder in your Github Repo. ""repo_subpath": "Halo Theme"," expects it to be inside a Folder called "Halo Theme". Also the Checkboxes need to be [x], not [ x]

**Comment by Jmotz85** [comment]
Thank you very much for the help, made the necessary changes and it should be good to go now.

**Comment by CaviarTheCatgirl** [comment]
From what I can see the Audio Pack Repo itself is good, but the Repo Commit changed which isnt reflected in the pack.json of this PR yet

**Comment by Jmotz85** [comment]
I updated it with the correct repo commit now, hopefully this does the trick lol

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by CaviarTheCatgirl** [comment]
Well from what I can see this should be good to go and it also passed the check now

**Comment by Jmotz85** [comment]
Sweet action, thank you again for the help!

Sent from my iPhone

On Oct 6, 2022, at 3:04 PM, DarkSide1305 ***@***.***> wrote:

﻿

Well from what I can see this should be good to go and it also passed the check now

**Review by beebls — APPROVED** [review]
All looks (and sounds) good

**Pull request merged**
