### PR TITLE
A bunch of Wii U OS songs

### PR DESCRIPTION
**Pull request by Haxorzz**
# Wii U mii maker menu (gamepad), friends list, dl management, settings (tv)

https://github.com/Haxorzz/Deck-audioloader-mine

### Checklist

Failure to complete this checklist or deleting boxes from the checklist will result in the closing of your pull request unless this is a pack update. Please write any comments regarding this checklist at the bottom of your pull request.

Check every box.

- [x] I am the original author of this pack or have permission from the original author to make this pull request.
- [x] All copyright of this pack's contents belong to the listed author or is cited in the description and repository linked above.
- [x] This theme works properly on the latest versions of SteamOS for Steam Deck, [decky-loader](https://github.com/SteamDeckHomebrew/decky-loader) and [SDH-AudioLoader](https://github.com/EMERALD0874/SDH-AudioLoader).
- [x] This pack is under 10MB in size and uses the least disk space possible.
- [x] This pack is safe for work and does not contain any sexual, drug-related, or profane content.
- [x] This pack does not contain loud, distorted, or otherwise bad faith sound files.
- [x] This pack is only for either music or sounds and only adds or modifies the intended sound files.

### CODE REVIEW

**Review by EMERALD0874 — CHANGES_REQUESTED** [review]
Looks like your repo commit ID is invalid. Please change it for all your JSON files to the most recent valid commit ID (in this case, [e2d13e1](https://github.com/Haxorzz/Deck-audioloader-mine/commit/e2d13e1817d170d61c1d27e048ad98183bbe470f)).

**Comment by Haxorzz** [comment]
That should do it....

**Comment by Haxorzz** [comment]
oh god one sec

**Comment by Haxorzz** [comment]
Ok now next check should NOT fail

**Comment by Haxorzz** [comment]
That's, weird. Do I need to update something here for it to register that I changed the file names...

**Comment by Haxorzz** [comment]
Ok, there was no documentation on what the "repo commit" really meant in the json, now I understand it should be the commit on your music files repo

**Comment by Haxorzz** [comment]
There we go, it's building like a charm

**Review by EMERALD0874 — APPROVED** [review]
LGTM

**Pull request merged**
