### PR TITLE
NieR Automata OS SFX + Music

### PR DESCRIPTION
**Pull request by WhoTheFlower**
# Insert Pack Name(s) Here

[NieR Perfect YoRHa OS Sound FX](https://github.com/WhoTheFlower/Steam-Deck-UI-Components/tree/main/NieR%20Perfect%20YoRHa%20OS%20Sound%20FX)
[Fortress of Lies - NieR Automata](https://github.com/WhoTheFlower/Steam-Deck-UI-Components/tree/main/Fortress%20of%20Lies%20-%20NieR%20Automata)
[Blissful Death - NieR Automata](https://github.com/WhoTheFlower/Steam-Deck-UI-Components/tree/main/Blissful%20Death%20-%20NieR%20Automata)
[Song of the Ancients, Devola - NieR](https://github.com/WhoTheFlower/Steam-Deck-UI-Components/tree/main/Song%20of%20the%20Ancients%2C%20Devola%20-%20NieR%20Replicant)
[Song of the Ancients, Popola - NieR](https://github.com/WhoTheFlower/Steam-Deck-UI-Components/tree/main/Song%20of%20the%20Ancients%2C%20Popola%20-%20NieR%20Replicant)

https://github.com/WhoTheFlower/Steam-Deck-UI-Components

### Checklist

Failure to complete this checklist or deleting boxes from the checklist will result in the closing of your pull request unless this is a pack update. Please write any comments regarding this checklist at the bottom of your pull request.

Check every box.

- [x] I am the original author of this pack or have permission from the original author to make this pull request.
- [x] All copyright of this pack's contents belong to the listed author or is cited in the description and repository linked above.
- [x] This theme works properly on the latest versions of SteamOS for Steam Deck, [decky-loader](https://github.com/SteamDeckHomebrew/decky-loader) and [SDH-AudioLoader](https://github.com/EMERALD0874/SDH-AudioLoader).
- [x] This pack is under 10MB in size and uses the least disk space possible.
- [x] This pack is safe for work and does not contain any sexual, drug-related, or profane content.
- [x] This pack does not contain loud, distorted, or otherwise bad faith sound files.
- [x] This pack is only for either music or sounds and only adds or modifies the intended sound files.

### CODE REVIEW

**Review by EMERALD0874 — CHANGES_REQUESTED** [review]
You need to either include or ignore deck_ui_message_toast.wav. You are also uploading an unnecessary cover image.

**Comment by WhoTheFlower** [comment]
Changes have been made, extra image is future-proofing in later update (very soon)

**Review by EMERALD0874 — DISMISSED** [review]
Same issue with deck_ui_message_toast.wav. Please make sure you read the entire guide on how to create a sound pack. Also, I'll wait until the future update before approving images/Who6464/NieR Replicant Cover.jpg. Please either include that update in this PR or remove the image.

**Comment by WhoTheFlower** [comment]
I ignored deck_ui_message_toast.wav, I'll work on adding my music packs so it can be in the same pull request

**Comment by WhoTheFlower** [comment]
Should be FIxed Now

**Comment by beebls** [comment]
All of the music packs work beautifully, however the YoRHa OS Sound FX pack's json file has an error.

```	
        "deck_ui_switch_toggle_off.wav",
	"deck_ui_switch_toggle_on.wav"
	"deck_ui_message_toast.wav"
	]
}
```

The "deck_ui_switch_toggle_on.wav" does not have a comma after it, so the JSON is not valid, and as such AudioLoader can't parse it.

If you add that comma, the pack works perfectly.

Please add a comma to the JSON file there, run it through a JSON validator just to be safe, and then update your PR and I will approve it.

**Comment by WhoTheFlower** [comment]
Updated, added the comma

**Review by beebls — CHANGES_REQUESTED** [review]
For your Nier Replicant packs, you don't link the full path of the image, just the name.
This is causing the CI to fail, please change the image path to "images/Who6464/NieR Replicant Cover.jpg"

**Comment by WhoTheFlower** [comment]
Fixed

**Review by beebls — APPROVED** [review]

**Pull request merged**
