### PR TITLE
Boneworks - Ambient A, Boneworks - Existence, Demon's Souls - Souls of Mist, XMB sounds

### PR DESCRIPTION
**Pull request by MadmanEpic**
# Insert Pack Name(s) Here

[Boneworks - Ambient A](https://github.com/MadmanEpic/AudioPacks/tree/main/Boneworks%20Ambient%20A)
[Boneworks - Existence](https://github.com/MadmanEpic/AudioPacks/tree/main/Boneworks%20Existence)
[Demon's Souls - Souls of Mist](https://github.com/MadmanEpic/AudioPacks/tree/main/Souls%20of%20Mist)
[XMB](https://github.com/MadmanEpic/AudioPacks/tree/main/XMB)

### Checklist

Failure to complete this checklist or deleting boxes from the checklist will result in the closing of your pull request unless this is a pack update. Please write any comments regarding this checklist at the bottom of your pull request.

Check every box.

- [x] I am the original author of this pack or have permission from the original author to make this pull request.
- [x] All copyright of this pack's contents belong to the listed author or is cited in the description and repository linked above.
- [x] This theme works properly on the latest versions of SteamOS for Steam Deck, [decky-loader](https://github.com/SteamDeckHomebrew/decky-loader) and [SDH-AudioLoader](https://github.com/EMERALD0874/SDH-AudioLoader).
- [x] This pack is under 10MB in size and uses the least disk space possible.
- [x] This pack is safe for work and does not contain any sexual, drug-related, or profane content.
- [x] This pack does not contain loud, distorted, or otherwise bad faith sound files.
- [x] This pack is only for either music or sounds and only adds or modifies the intended sound files.

### CODE REVIEW

**Comment by beebls** [comment]
The repo commit that you have listed for all of your packs is not one that exists.

Change it to "03aa1ac" as that is the most recent commit of your repo.

**Review by beebls — DISMISSED** [review]
The repo commit that you have listed for all of your packs is not one that exists.

Change it to `03aa1ac` as that is the most recent commit of your repo.

**Comment by MadmanEpic** [comment]
Didn't catch that, should be resolved now.

> The repo commit that you have listed for all of your packs is not one that exists.
> 
> Change it to `03aa1ac` as that is the most recent commit of your repo.

Missed that, should be resolved now.

**Comment by beebls** [comment]
Thanks for fixing that so quickly, however there appears to be another issue.
Your XMB sound pack has some sounds that have a file _and_ are referenced in the ignore field.
Please go through it and ensure that each sound effect is either a file, or ignored, then the CI should run successfully.

**Comment by MadmanEpic** [comment]
Updated the XMB ignores, didn't realize it would cause an issue since it didn't seem to cause issues when I was testing it. Hopefully all good now.

**Comment by beebls** [comment]
`Pack is missing ui_steam_message_old_smooth.m4a`

It appears not every sound was fixed lol.
The pack will still work locally, it's just that the CI ensures there are no duplicates in order for a theme to be merged.

**Comment by MadmanEpic** [comment]
Should _hopefully, actually_ be good now, Windows shuffled that one to the end of the folder because it was .m4a so I didn't catch it. Sorry about hitting every branch on the way down the tree here, I couldn't get the checker to work locally.

**Review by beebls — APPROVED** [review]
All works now after a little trial and error

**Comment by beebls** [comment]
> Should _hopefully, actually_ be good now, Windows shuffled that one to the end of the folder because it was .m4a so I didn't catch it. Sorry about hitting every branch on the way down the tree here, I couldn't get the checker to work locally.

All good lol, glad we could sort it out

**Pull request merged**
