### PR TITLE
Added YGOFM SFX and Free Duel Music Packs

### PR DESCRIPTION
**Pull request by stewartisme**
Added YGOFM SFX and Free Duel Music Packs

Yu-Gi-Oh! Forbidden Memories - SFX
Yu-Gi-Oh! Forbidden Memories - Free Duel

https://github.com/stewartisme/Steam-Deck-AudioLoader-Packs

### Checklist

Failure to complete this checklist or deleting boxes from the checklist will result in the closing of your pull request unless this is a pack update. Please write any comments regarding this checklist at the bottom of your pull request.

Check every box.

- [x ] I am the original author of this pack or have permission from the original author to make this pull request.
- [x ] All copyright of this pack's contents belong to the listed author or is cited in the description and repository linked above.
- [x ] This theme works properly on the latest versions of SteamOS for Steam Deck, [decky-loader](https://github.com/SteamDeckHomebrew/decky-loader) and [SDH-AudioLoader](https://github.com/EMERALD0874/SDH-AudioLoader).
- [x ] This pack is under 10MB in size and uses the least disk space possible.
- [x ] This pack is safe for work and does not contain any sexual, drug-related, or profane content.
- [x ] This pack does not contain loud, distorted, or otherwise bad faith sound files.
- [x ] This pack is only for either music or sounds and only adds or modifies the intended sound files.

### CODE REVIEW

**Comment by EMERALD0874** [comment]
Due to recent concerns regarding copyrighted material, approvals for music packs are currently on hold. If your song meets one of the following requirements, please let us know by putting a comment on this pull request. Otherwise, please expect a verdict regarding copyrighted songs in the next week or so.

- Original compositions and performances
- Copyright-free and public domain performances
- Music from other console operating system menus\*

\**Operating system songs must still be approved by repository maintainers. Unnecessary songs and songs from first-party applications (ex. Wii Shop, Nintendo eShop) may be denied.*

**Comment by stewartisme** [comment]
I removed the free duel music and left the SFX.

**Review by EMERALD0874 — CHANGES_REQUESTED** [review]
Looks like you're attempting to ignore some files in your pack. Please either remove the sound files or remove the file names from your ignore array. Feel free to request a new review once you've made your changes.

**Comment by EMERALD0874** [comment]
Your music pack is being denied due to new copyright requirements, but we will continue to review your sound pack. #60

**Comment by stewartisme** [comment]
Removed the extra files so hopefully it is fine now.

**Review by EMERALD0874 — CHANGES_REQUESTED** [review]
You need to update your repo commit ID so that your changes are reflected here.

For your convenience: `6f7f630`

**Review by EMERALD0874 — APPROVED** [review]
I'm just an itsy bitsy bit dumb and forgot to check if you gave me permission to edit your JSON. Looks good now that the commit ID has been updated and your files sound good to go.

Approved and merged.

**Comment by stewartisme** [comment]
Are soundtrack things allowed now?

**Pull request merged**
