### PR TITLE
SMT3 Menu SFX

### PR DESCRIPTION
**Pull request by RadsammyT**
# SMT3 Menu SFX
[Insert a link to the GitHub repository of the pack.
](https://github.com/RadsammyT/Audio-loader-SD/tree/master/SMT3%20Menu%20SFX)
### Requirements Agreement

Failure to check the box below by writing an X between the brackets will result in the closing of your pull request. Please write any comments regarding issues with the requirements below.

- [x] I have read [the pack requirements](https://github.com/EMERALD0874/AudioLoader-PackDB#-requirements). I understand that if my pull request does not meet them, it will be closed and I may be banned from the pack database.

### CODE REVIEW

**Comment by RadsammyT** [comment]
i think i forgot to update my commit ID hold on

**Review by EMERALD0874 — CHANGES_REQUESTED** [review]
`Exception: Duplicate entry: deck_ui_message_toast.wav is in ignore and is present as a file.`

**Comment by RadsammyT** [comment]
VbcU2MPYH9
LYoH4VYi4z
PAWPmlhHUJ
im just confused right now. commit ID _should_ be the latest as linked in the repo but I am very unsure why it thinks that file is both in my linked repo and listed as ignored in my fork

**Comment by RadsammyT** [comment]
ok this just got more confusing, #75 's checks also failed for the same reason, and in the same circumstances as mine (file listed as ignored and is not present in linked repo yet main.py throws it)

 
AFEwBwy1IA

GhwzoQfQWC

oHKkHFkJNO

**Comment by EMERALD0874** [comment]
Looking into it, gimme a sec

**Comment by EMERALD0874** [comment]
Can you please rebase from master? I think it has to do with a pack that broke some things earlier.

**Comment by RadsammyT** [comment]
rebased (hopefully), try now

**Review by EMERALD0874 — APPROVED** [review]
Passed CLI so I'm going to assume everything is good lol. Been a long week

**Pull request merged**
