### PR TITLE
Add Wii Theme

### PR DESCRIPTION
**Pull request by OT-Archmage**
# Wii Theme

[Insert a link to the GitHub repository of the pack.](https://github.com/OT-Archmage/SteamDeckCustomisations/tree/main/Sound%20Packs/Wii%20Menu%20Sound%20Pack)

### Checklist

Failure to complete this checklist or deleting boxes from the checklist will result in the closing of your pull request unless this is a pack update. Please write any comments regarding this checklist at the bottom of your pull request.

Check every box.

- [x] I am the original author of this pack or have permission from the original author to make this pull request.
- [x] All copyright of this pack's contents belong to the listed author or is cited in the description and repository linked above.
- [x] This theme works properly on the latest versions of SteamOS for Steam Deck, [decky-loader](https://github.com/SteamDeckHomebrew/decky-loader) and [SDH-AudioLoader](https://github.com/EMERALD0874/SDH-AudioLoader).
- [x] This pack is under 10MB in size and uses the least disk space possible.
- [x] This pack is safe for work and does not contain any sexual, drug-related, or profane content.
- [x] This pack does not contain loud, distorted, or otherwise bad faith sound files.
- [x] This pack is only for either music or sounds and only adds or modifies the intended sound files.

### CODE REVIEW

**Review by EMERALD0874 — CHANGES_REQUESTED** [review]
The sound for starting a game is pulled from starting the console, not a game. Is there any chance you could replace it with [the proper sound](https://youtu.be/rMDW4jYuYAU?t=87)? This would ensure accuracy and avoid overlap with a Wii menu music pack in the future. Other than that, everything looks and sounds great! Thank you for making this!

**Comment by OT-Archmage** [comment]
I was actually working on an accompanying music pack using track 2 from [the khinsider Wii Menu Gamerip album.](https://downloads.khinsider.com/game-soundtracks/album/wii-system-menu) The reason I made that sound the "launch game" sound rather than including it in the music pack is because it only plays once at the start and doesn't fit into a proper loop, unless the plugin has a way to have an intro track that transitions into a separate looping track.

I get what you mean about accuracy though, so I've changed the sound like you suggested.

**Comment by OT-Archmage** [comment]
[Also here's the link to the Music Pack.](https://github.com/OT-Archmage/SteamDeckCustomisations/tree/main/Sound%20Packs/Wii%20Menu%20Music%20Pack)

**Comment by EMERALD0874** [comment]
> unless the plugin has a way to have an intro track that transitions into a separate looping track.

This is a great idea. I have created https://github.com/EMERALD0874/SDH-AudioLoader/issues/11 to help with this implementation.

**Review by EMERALD0874 — APPROVED** [review]
LGTM

**Pull request merged**
