### PR TITLE
History from Sonic Mega Collection

### PR DESCRIPTION
**Pull request by Suwazo**
# History SMC

https://github.com/Suwazo/History-AudioLoader

### Checklist

Failure to complete this checklist or deleting boxes from the checklist will result in the closing of your pull request unless this is a pack update. Please write any comments regarding this checklist at the bottom of your pull request.

Check every box.

- [x] I am the original author of this pack or have permission from the original author to make this pull request.
- [x] All copyright of this pack's contents belong to the listed author or is cited in the description and repository linked above.
- [x] This theme works properly on the latest versions of SteamOS for Steam Deck, [decky-loader](https://github.com/SteamDeckHomebrew/decky-loader) and [SDH-AudioLoader](https://github.com/EMERALD0874/SDH-AudioLoader).
- [x] This pack is under 10MB in size and uses the least disk space possible.
- [x] This pack is safe for work and does not contain any sexual, drug-related, or profane content.
- [x] This pack does not contain loud, distorted, or otherwise bad faith sound files.
- [x] This pack is only for either music or sounds and only adds or modifies the intended sound files.

### CODE REVIEW

**Comment by beebls** [comment]
Your `Suwazo-History SMC` file does not have a file extension, and as such is not being recognized by the CI.

To fix, change it to `Suwazo-History SMC.json`

**Review by beebls — CHANGES_REQUESTED** [review]
Your `Suwazo-History SMC` file does not have a file extension, and as such is not being recognized by the CI.

To fix, change it to `Suwazo-History SMC.json`

**Comment by Suwazo** [comment]
Committed the requested change, apologies. And apologies for my lack of Github knowledge, it still says changes are requested but hopefully this is normal and I haven't done this the wrong way.
Ran main.py and got the pack output as a zip folder so I assume this means this functions as expected. Though the folder in the zip is just "History" rather than "History SMC", had tried avoiding this in case similarly named songs got added in the future but I guess this is taken from the name field, I think that and the image filename are the only places I used it.

**Comment by EMERALD0874** [comment]
Due to recent concerns regarding copyrighted material, approvals for music packs are currently on hold. If your song meets one of the following requirements, please let us know by putting a comment on this pull request. Otherwise, please expect a verdict regarding copyrighted songs in the next week or so.

- Original compositions and performances
- Copyright-free and public domain performances
- Music from other console operating system menus\*

\**Operating system songs must still be approved by repository maintainers. Unnecessary songs and songs from first-party applications (ex. Wii Shop, Nintendo eShop) may be denied.*

**Comment by EMERALD0874** [comment]
This pull request is being denied due to new copyright requirements. #60

**Pull request closed without merging**
