### PR TITLE
Sonic the Hedgehog & Sonic Mania SFX

### PR DESCRIPTION
**Pull request by AcumaKai**
Sonic the Hedgehog, Sonic Mania.

https://github.com/AcumaKai/Steam-Deck-Sound-Packs

### Checklist

Failure to complete this checklist or deleting boxes from the checklist will result in the closing of your pull request unless this is a pack update. Please write any comments regarding this checklist at the bottom of your pull request.

Check every box.

- [x] I am the original author of this pack or have permission from the original author to make this pull request.
- [x] All copyright of this pack's contents belong to the listed author or is cited in the description and repository linked above.
- [x] This theme works properly on the latest versions of SteamOS for Steam Deck, [decky-loader](https://github.com/SteamDeckHomebrew/decky-loader) and [SDH-AudioLoader](https://github.com/EMERALD0874/SDH-AudioLoader).
- [x] This pack is under 10MB in size and uses the least disk space possible.
- [x] This pack is safe for work and does not contain any sexual, drug-related, or profane content.
- [x] This pack does not contain loud, distorted, or otherwise bad faith sound files.
- [x] This pack is only for either music or sounds and only adds or modifies the intended sound files.

### CODE REVIEW

**Comment by EMERALD0874** [comment]
Due to recent concerns regarding copyrighted material, approvals for music packs are currently on hold. If your song meets one of the following requirements, please let us know by putting a comment on this pull request. Otherwise, please expect a verdict regarding copyrighted songs in the next week or so.

- Original compositions and performances
- Copyright-free and public domain performances
- Music from other console operating system menus\*

\**Operating system songs must still be approved by repository maintainers. Unnecessary songs and songs from first-party applications (ex. Wii Shop, Nintendo eShop) may be denied.*

**Comment by AcumaKai** [comment]
> Due to recent concerns regarding copyrighted material, approvals for music packs are currently on hold. If your song meets one of the following requirements, please let us know by putting a comment on this pull request. Otherwise, please expect a verdict regarding copyrighted songs in the next week or so.
> 
>     * Original compositions and performances
> 
>     * Copyright-free and public domain performances
> 
>     * Music from other console operating system menus*
> 
> 
> *_Operating system songs must still be approved by repository maintainers. Unnecessary songs and songs from first-party applications (ex. Wii Shop, Nintendo eShop) may be denied._

The "Sonic the Hedgehog" and "Sonic Mania" sound effects are the only two which aren't music. The rest are from games, so they are copyrighted. Not sure how much fair use comes in to play here tbh.

**Comment by EMERALD0874** [comment]
The issue is this may not be considered fair use due to us more or less being an over-glorified MP3 storage system. While I doubt most groups will care about their UI sound effects being used elsewhere, I could see music quickly becoming an issue.

**Review by EMERALD0874 — CHANGES_REQUESTED** [review]
The music packs within this pull request are being denied due to new copyright requirements. Once the music packs are removed, we will review the sound packs. #60

**Comment by AcumaKai** [comment]
Yeah, that's totally understandable. Better safe than sorry. At least it's not too hard to add music for personal use. I'll get the music removed soon.

**Comment by AcumaKai** [comment]
> The music packs within this pull request are being denied due to new copyright requirements. Once the music packs are removed, we will review the sound packs. #60

I've deleted the music and all the associated files.

How would remixes and covers versions of VGM work, would that be acceptable?

**Comment by EMERALD0874** [comment]
It would be acceptable if the copyright holder has given you or all audiences permission to use it in their creative works. However, music should still be something that makes sense as a menu song and we retain the right to deny any songs we think may not see much use. At this time, we have a limited database size and we want to avoid too much unnecessary use.

**Review by EMERALD0874 — APPROVED** [review]
Sounds great!

Approved and merged.

**Comment by AcumaKai** [comment]
Thanks!

Not sure where else to post this. I'm certain these do get used. I can at least confirm 'ui_steam_smoother_friend_online.m4a' plays when a friend comes online.

steam_at_mention.m4a - You'd hear this if you were @ mentioned in chat/group chat.
steam_chatroom_notification.m4a - You'd hear this when you get a message from a group chatroom.
ui_steam_smoother_friend_join.m4a - I really don't know, but I assume it's when a friend joins a chat, group, game, or invite?
ui_steam_smoother_friend_online.m4a - This plays when a friend comes online if.

They only play if they're enabled in the settings.

Hope that info is useful to you.

**Comment by EMERALD0874** [comment]
Will update this, thank you. In the future, you can create an issue and tag it as documentation.

**Pull request merged**
