### PR TITLE
Persona5-Royal-Days

### PR DESCRIPTION
**Pull request by novaVR07**
# Persona5-Royal-Days
[Insert a link to the GitHub repository of the pack.](https://github.com/novaVR07/Royal-Days-From-Persona-5)

### Requirements Agreement

Failure to check the box below by writing an X between the brackets will result in the closing of your pull request. Please write any comments regarding issues with the requirements below.

- [x] I have read [the pack requirements](https://github.com/EMERALD0874/AudioLoader-PackDB#-requirements). I understand that if my pull request does not meet them, it will be closed and I may be banned from the pack database.

### CODE REVIEW

**Comment by EMERALD0874** [comment]
This pull request is being denied as it violates [the music requirements](https://github.com/EMERALD0874/AudioLoader-PackDB#-music-requirements).

**Comment by novaVR07** [comment]
Is there anything I can do make it meet the requirements?

**Comment by EMERALD0874** [comment]
No. It is a copyrighted piece of music.

**Comment by novaVR07** [comment]
Ok, thanks anyways

**Pull request closed without merging**
