### PR TITLE
Add Mii Channel Music

### PR DESCRIPTION
**Pull request by yuckdevchan**
# Mii Channel Music Pack

pack:
https://github.com/yuckdevchan/audiopacks

### Checklist

Failure to complete this checklist or deleting boxes from the checklist will result in the closing of your pull request unless this is a pack update. Please write any comments regarding this checklist at the bottom of your pull request.

Check every box.

- [ ✓] I am the original author of this pack or have permission from the original author to make this pull request.
- [ ✓] All copyright of this pack's contents belong to the listed author or is cited in the description and repository linked above.
- [ ✓] This theme works properly on the latest versions of SteamOS for Steam Deck, [decky-loader](https://github.com/SteamDeckHomebrew/decky-loader) and [SDH-AudioLoader](https://github.com/EMERALD0874/SDH-AudioLoader).
- [ ✓] This pack is under 10MB in size and uses the least disk space possible.
- [✓ ] This pack is safe for work and does not contain any sexual, drug-related, or profane content.
- [✓ ] This pack does not contain loud, distorted, or otherwise bad faith sound files.
- [✓ ] This pack is only for either music or sounds and only adds or modifies the intended sound files.

### CODE REVIEW

**Comment by beebls** [comment]
The menu_music.mp3 file is ~11.5MB, this is above our 10MB limit for packs. I noticed that it is a 10+ minute long song, the Mii Channel music is a short loop that is just repeated.
[I reccomend using a shorter clip like this,](https://www.youtube.com/watch?v=po-0n1BKW2w) as that would greatly reduce file size, and since audioloader loops menu music, it would still sound the same.

**Review by beebls — CHANGES_REQUESTED** [review]
As I said in the previous comment, please either reduce the file size of the music, or use a shorter clip to get it under the 10mb limit

**Comment by pearlyturbine** [comment]
> As I said in the previous comment, please either reduce the file size of the music, or use a shorter clip to get it under the 10mb limit

Okay, I'll do that when I have time then come back. 👍

**Comment by EMERALD0874** [comment]
Due to recent concerns regarding copyrighted material, approvals for music packs are currently on hold. If your song meets one of the following requirements, please let us know by putting a comment on this pull request. Otherwise, please expect a verdict regarding copyrighted songs in the next week or so.

- Original compositions and performances
- Copyright-free and public domain performances
- Music from other console operating system menus\*

\**Operating system songs must still be approved by repository maintainers. Unnecessary songs and songs from first-party applications (ex. Wii Shop, Nintendo eShop) may be denied.*

**Comment by EMERALD0874** [comment]
This pull request is being denied due to new copyright requirements. #60

**Pull request closed without merging**
