### PR TITLE
Fire Emblem Awakening

### PR DESCRIPTION
**Pull request by Rickopher**
# Fire Emblem Awakening

https://github.com/Rickopher/Steam-Deck-Sound-Sfx/tree/main/Fire%20Emblem%20Awakening

### Requirements Agreement

Failure to check the box below by writing an X between the brackets will result in the closing of your pull request. Please write any comments regarding issues with the requirements below.

- [X] I have read [the pack requirements](https://github.com/EMERALD0874/AudioLoader-PackDB#-requirements). I understand that if my pull request does not meet them, it will be closed and I may be banned from the pack database.

### CODE REVIEW

**Review by EMERALD0874 — CHANGES_REQUESTED** [review]
The pack is missing bumper_end.wav. Please ensure that all sounds are accounted for by either adding them to the ignore array, creating a sound file with its exact name, or mapping a file name to a different one using the README instructions.

**Comment by Rickopher** [comment]
Just updated the pack.json. All sounds should be accounted for.

**Comment by EMERALD0874** [comment]
You need to update your commit ID here every time you make changes.

**Comment by Rickopher** [comment]
Just updated the commit ID to match the current version

**Comment by Rickopher** [comment]
Sorry about that, hope it works now

**Review by EMERALD0874 — CHANGES_REQUESTED** [review]
You need to specify **the whole file name**, including the extension.

**Comment by Rickopher** [comment]
lots of whoops today it seems. It has been updated

**Review by EMERALD0874 — CHANGES_REQUESTED** [review]
Please make sure you have checked every single sound file name in the README before updating your PR again, please. It seems this may be an issue with multiple sounds.

**Comment by Rickopher** [comment]
Thank you for your patience

**Review by EMERALD0874 — APPROVED** [review]
LGTM

**Pull request merged**
